### ISSUE TITLE
Is this script working?

### ISSUE THREAD

**Issue by mbst83r** [GossiTheDog/scanning#4]
Hi, we patched our servers and scanned them again with that script. It shows, that they are still vulnerable.

Then we used the script from [MS](https://github.com/microsoft/CSS-Exchange/blob/main/Security/http-vuln-cve2021-26855.nse) and the result was that it was not vulnerable anymore. 

We tested this on a few exchange servers, patched with the latest CU and security updates.

Any thoughts?

**Comment by GossiTheDog** [comment]
hey - it says may be vulnerable and you should check security update is
applied.  This script can't check the Security Update part, just the CU
version - so if you fully updated, you should be okay.

**Comment by mbst83r** [comment]
OK, great. So we are fine ;-)

Thanks.

**Comment by GossiTheDog** [comment]
Great stuff!

**Comment by lukastribus** [comment]
I strongly suggest people use Microsoft's nmap script instead, which does proper detection:

https://github.com/microsoft/CSS-Exchange/blob/main/Security/src/http-vuln-cve2021-26855.nse
